### PR TITLE
add ability to create trace matrix from properties

### PR DESCRIPTION
**Pull request by davecap**

### CODE REVIEW

**Comment by davecap** [comment]
Sorry, this is not ready for review. Closing

**Comment by inorton** [comment]
Thanks Dave, I look forward to it.

**Comment by inorton** [comment]
Oh btw, we've moved to https://gitlab.com/inorton/junit2html

**Comment by davecap** [comment]
We've decided not to pursue this option unfortunately... sorry about that!

**Comment by inorton** [comment]
No worries Dave :)

**Pull request closed without merging**
